version: '3'
services:
  mulearnbackend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mulearnbackend
    image: mulearnbackend
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - /var/log/mulearnbackend:/var/log/mulearnbackend
      - /var/www/mulearnbackend/assets:/app/mulearnbackend
      - /var/www/media/assets:/app/media
    env_file:
      - .env
